POST http://127.0.0.1:7823/connect
Content-Type: application/json

{
  "jdbcUrl": "jdbc:mysql://localhost:3306/test",
  "driver": "com.mysql.cj.jdbc.Driver",
  "driverPath": "D:/mysql-connector-java-8.0.29.jar",
  "username": "root",
  "password": "root",
  "id": "mysql-test"
}

### SQLITE
POST http://127.0.0.1:7823/connect
Content-Type: application/json

{
  "jdbcUrl": "jdbc:sqlite:D:/test.db",
  "driver": "org.sqlite.JDBC",
  "driverPath": "D:/sqlite-jdbc-3.36.0.3.jar",
  "id": "sqlite-test23"
}
